export const REMOVE_ALL = 'REMOVE_ALL';
export const REMOVE_SELECTED = 'REMOVE_SELECTED';
// layout actions
export const SET_HEADER_HEIGHT = 'SET_HEADER_HEIGHT';
export const TOGGLE_NAVIGATION_VISIBILITY = 'TOGGLE_NAVIGATION_VISIBILITY';
// --> saga listeners
export const HANDLE_NAVIGATION_VISIBILITY= 'HANDLE_NAVIGATION_VISIBILITY';
export const HANDLE_HEADER_HEIGHT = 'HANDLE_HEADER_HEIGHT';
