export const REMOVE_ALL = 'REMOVE_ALL';
export const REMOVE_SELECTED = 'REMOVE_SELECTED';
// layout actions
export const SET_HEADER_HEIGHT = 'SET_HEADER_HEIGHT';
export const TOGGLE_NAVIGATION_VISIBILITY = 'TOGGLE_NAVIGATION_VISIBILITY';
export const TOGGLE_NAVIGATION_SIZE = 'TOGGLE_NAVIGATION_SIZE';
export const SET_SECTION_HEIGHT = 'SET_SECTION_HEIGHT';
export const SET_MAIN_SCROLL ='SET_MAIN_SCROLL'

// --> saga listeners
export const HANDLE_NAVIGATION_VISIBILITY= 'HANDLE_NAVIGATION_VISIBILITY';
export const HANDLE_NAVIGATION_SIZE= 'HANDLE_NAVIGATION_SIZE';
export const HANDLE_HEADER_HEIGHT = 'HANDLE_HEADER_HEIGHT';
export const HANDLE_SECTION_SIZE = 'HANDLE_SECTION_SIZE';
export const HANDLE_MAIN_SCROLL ='HANDLE_MAIN_SCROLL'
